import { getAllPages } from '@/utils'
import {
  ROUTE_ARTICLE_EDIT,
  ROUTE_LOGIN,
  ROUTE_PROFILE,
  ROUTE_REGISTER,
  ROUTE_RPG_FULL,
  ROUTE_RPG_GUIDE,
} from './routes'

export {
  ROUTE_ABOUT,
  ROUTE_ARCHIVES,
  ROUTE_ARTICLE_EDIT,
  ROUTE_CATEGORY_LIST,
  ROUTE_DETAIL,
  ROUTE_EXPLORE,
  ROUTE_FEATURES,
  ROUTE_HOME,
  ROUTE_LINKS,
  ROUTE_LOGIN,
  ROUTE_ME,
  ROUTE_MSGBOARD,
  ROUTE_NOT_FOUND,
  ROUTE_PROFILE,
  ROUTE_PROJECTS,
  ROUTE_REGISTER,
  ROUTE_RPG_ENTRY,
  ROUTE_RPG_FULL,
  ROUTE_RPG_GUIDE,
  ROUTE_SEARCH,
  ROUTE_TAG_LIST,
  ROUTE_TOOL_INDEX,
  ROUTE_USER_PUBLIC,
} from './routes'

export const LOGIN_STRATEGY_MAP = {
  DEFAULT_NO_NEED_LOGIN: 0,
  DEFAULT_NEED_LOGIN: 1,
}
export const LOGIN_STRATEGY = LOGIN_STRATEGY_MAP.DEFAULT_NO_NEED_LOGIN
export const isNeedLoginMode = LOGIN_STRATEGY === LOGIN_STRATEGY_MAP.DEFAULT_NEED_LOGIN

export const LOGIN_PAGE = ROUTE_LOGIN
export const REGISTER_PAGE = ROUTE_REGISTER

export const LOGIN_PAGE_LIST = [LOGIN_PAGE, REGISTER_PAGE]

export const excludeLoginPathList = getAllPages('excludeLoginPath').map(page => page.path)

/** 黑名单：需登录才能访问的页面（默认无需登录策略下） */
export const NEED_LOGIN_PATH_LIST = [
  ROUTE_PROFILE,
  ROUTE_ARTICLE_EDIT,
  ROUTE_RPG_FULL,
  ROUTE_RPG_GUIDE,
]

export const EXCLUDE_LOGIN_PATH_LIST = [
  ...NEED_LOGIN_PATH_LIST,
  ...excludeLoginPathList,
]

export const LOGIN_PAGE_ENABLE_IN_MP = false
